// <auto-generated />
using System;
using ManaChaiLeasing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManaChaiLeasing.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

        modelBuilder.Entity("ManaChaiLeasing.Models.AppSetting", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("InterestPeriodDays").HasColumnType("INTEGER");
            b.Property<decimal>("InterestRatePercent").HasPrecision(8, 2).HasColumnType("TEXT");
            b.Property<string>("StoreName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

            b.HasKey("Id");
            b.ToTable("AppSettings");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.Customer", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("Address").HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<int?>("Age").HasColumnType("INTEGER");
            b.Property<string>("CitizenId").HasMaxLength(13).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Phone").HasMaxLength(30).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

            b.HasKey("Id");
            b.HasIndex("CitizenId").IsUnique();
            b.ToTable("Customers");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.PawnTicket", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("Accessories").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("AssetCategory").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Brand").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("CapacityOrSize").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Color").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Condition").HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<int>("CustomerId").HasColumnType("INTEGER");
            b.Property<string>("ImeiOrSerial").HasMaxLength(150).HasColumnType("TEXT");
            b.Property<int>("InterestPeriodDays").HasColumnType("INTEGER");
            b.Property<decimal>("InterestRatePercent").HasPrecision(8, 2).HasColumnType("TEXT");
            b.Property<string>("Model").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Note").HasMaxLength(1500).HasColumnType("TEXT");
            b.Property<string>("OtherDetails").HasMaxLength(1500).HasColumnType("TEXT");
            b.Property<DateTime>("PawnDate").HasColumnType("TEXT");
            b.Property<decimal>("PrincipalAmount").HasPrecision(18, 2).HasColumnType("TEXT");
            b.Property<string>("ProductSummary").IsRequired().HasMaxLength(2500).HasColumnType("TEXT");
            b.Property<string>("ProductType").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Specification").HasMaxLength(1500).HasColumnType("TEXT");
            b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
            b.Property<string>("TicketNumber").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

            b.HasKey("Id");
            b.HasIndex("CustomerId");
            b.HasIndex("TicketNumber").IsUnique();
            b.ToTable("PawnTickets");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.PawnTransaction", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("TEXT");
            b.Property<string>("CashFlowType").IsRequired().HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<int?>("InterestSequence").HasColumnType("INTEGER");
            b.Property<bool>("IsVoided").HasColumnType("INTEGER");
            b.Property<string>("Note").HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<int>("PawnTicketId").HasColumnType("INTEGER");
            b.Property<string>("PaymentMethod").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("TransactionDate").HasColumnType("TEXT");
            b.Property<string>("TransactionType").IsRequired().HasColumnType("TEXT");
            b.Property<string>("VoidReason").HasMaxLength(500).HasColumnType("TEXT");

            b.HasKey("Id");
            b.HasIndex("PawnTicketId");
            b.ToTable("PawnTransactions");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.SmartLookupValue", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("FieldType").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("LastUsedAt").HasColumnType("TEXT");
            b.Property<string>("NormalizedValue").IsRequired().HasMaxLength(250).HasColumnType("TEXT");
            b.Property<int>("UsageCount").HasColumnType("INTEGER");
            b.Property<string>("Value").IsRequired().HasMaxLength(250).HasColumnType("TEXT");

            b.HasKey("Id");
            b.HasIndex("FieldType", "Category", "NormalizedValue").IsUnique();
            b.ToTable("SmartLookupValues");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.PawnTicket", b =>
        {
            b.HasOne("ManaChaiLeasing.Models.Customer", "Customer")
                .WithMany("PawnTickets")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Customer");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.PawnTransaction", b =>
        {
            b.HasOne("ManaChaiLeasing.Models.PawnTicket", "PawnTicket")
                .WithMany("Transactions")
                .HasForeignKey("PawnTicketId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("PawnTicket");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.Customer", b =>
        {
            b.Navigation("PawnTickets");
        });

        modelBuilder.Entity("ManaChaiLeasing.Models.PawnTicket", b =>
        {
            b.Navigation("Transactions");
        });
#pragma warning restore 612, 618
    }
}
